modLoader="javafml"
loaderVersion="[35,)"
license="Academic Free License v3.0"

[[mods]]
modId="quashconomiestwo"
version="1.0.0"
displayName="Quashconomies Two"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="KingdomsMC"
description='''
Quashconomies mod for the Duelist Kingdoms server!
'''

[[dependencies.quashconomiestwo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




